return {
  'nvim-treesitter/nvim-treesitter',
  event = { 'BufReadPost', 'BufNewFile' },
  build = ':TSUpdate',
  main = 'nvim-treesitter.configs',
  opts = {
    auto_install = true,
    highlight = {
      enable = true,
      additional_vim_regex_highlighting = { 'ruby' },
    },
    indent = { enable = true, disable = { 'ruby' } },
    incremental_selection = {
      enable = true,
      keymaps = {
        init_selection = '<Enter>', -- set to `false` to disable one of the mappings
        node_incremental = '<Enter>',
        scope_incremental = false,
        node_decremental = '<Backspace>',
      },
    },
    -- Parser list: https://github.com/tree-sitter/tree-sitter/wiki/List-of-parsers
    ensure_installed = {
      'bash',
      'cmake',
      'css',
      'csv',
      'diff',
      'dockerfile',
      'git_config',
      'gitattributes',
      'gitcommit',
      'gitignore',
      'gitignore',
      'go',
      'graphql',
      'groovy',
      'html',
      'java',
      'javascript',
      'json',
      'lua',
      'luadoc',
      'make',
      'make',
      'markdown',
      'markdown_inline',
      'nix',
      'python',
      'query',
      'regex',
      'requirements',
      'sql',
      'sql',
      'ssh_config',
      'terraform',
      'tmux',
      'toml',
      'tsx',
      'typescript',
      'yaml',
    },
  },
}
