name: Lua Lint Check
on: [push, pull_request]
jobs:
  lint:
    name: Lint Lua with Selene
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install Selene
        run: |
          curl -fsSL https://github.com/Kampfkarren/selene/releases/download/0.28.0/selene-0.28.0-linux.zip -o selene.zip
          unzip -q selene.zip
          chmod +x selene
      - name: Run Selene Lint
        run: ./selene .
